version: 2

jobs:
  build:
    docker:
      - image: mono:onbuild
    steps:
      - checkout
      - run:
          name: Setup NUnit
          command: nuget install NUnit.Runners
       - run:
          name: Run the Test Command
          command: mono ./NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe GalaxyShooterInternalsTest.dll -noresult
