version: 2

jobs:
  build:
    docker:
      - image: mono:onbuild
    steps:
      - checkout
      - run:
          name: Setup NUnit
          command: nuget install NUnit.Runners && nuget restore ./GalaxyShooterInternals.sln
      - run:
          name: Build Project
          command: xbuild ./GalaxyShooterInternals.sln     
      - run:
          name: Run the Test Command
          command: mono ./NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./GalaxyShooterInternalsTest/bin/Debug/GalaxyShooterInternalsTest.dll -noresult
