version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Image
          command: docker build -t test-build .
      - run:
          name: Run the Test Command
          command: docker run test-build ./NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe GalaxyShooterInternalsTest.dll -noresult
